gen:
	fvm flutter pub run build_runner build --delete-conflicting-outputs

watch:
	fvm flutter pub run build_runner watch --delete-conflicting-outputs

run:
	fvm flutter run -d chrome --web-port=8080

clean_gen:
	rm -rvf *.g.dart
	
.PHONY: gen watch run

