name: lively
description: Zero-boilerplate reactive Flutter widgets via code generation.
version: 1.0.1
homepage: https://github.com/Oualitsen/lively
repository: https://github.com/Oualitsen/lively
issue_tracker: https://github.com/Oualitsen/lively/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lively_generator:
    path: ./lively_generator
  build_runner: ^2.4.0
