builders:
  lively_generator:
    import: "package:lively_generator/builder.dart"
    builder_factories: ["livelyBuilder"]
    build_extensions: {".dart": [".lively.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
